# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/chenhaoliang/chl/大学课程作业等/大三下/GIS设计与应用/work1/PiGIS/ui/raw/_attributesTable.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AttributesTable(object):
    def setupUi(self, AttributesTable):
        AttributesTable.setObjectName("AttributesTable")
        AttributesTable.resize(739, 401)
        AttributesTable.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.gridLayout = QtWidgets.QGridLayout(AttributesTable)
        self.gridLayout.setObjectName("gridLayout")
        self.dataTable = QtWidgets.QTableWidget(AttributesTable)
        self.dataTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.dataTable.setObjectName("dataTable")
        self.dataTable.setColumnCount(5)
        self.dataTable.setRowCount(5)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.dataTable.setItem(2, 2, item)
        self.gridLayout.addWidget(self.dataTable, 1, 0, 1, 1)
        self.widget = QtWidgets.QWidget(AttributesTable)
        self.widget.setMinimumSize(QtCore.QSize(0, 25))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.editFieldButton = QtWidgets.QToolButton(self.widget)
        self.editFieldButton.setObjectName("editFieldButton")
        self.horizontalLayout.addWidget(self.editFieldButton)
        self.addItemButton = QtWidgets.QToolButton(self.widget)
        self.addItemButton.setObjectName("addItemButton")
        self.horizontalLayout.addWidget(self.addItemButton)
        self.deleteItemButton = QtWidgets.QToolButton(self.widget)
        self.deleteItemButton.setObjectName("deleteItemButton")
        self.horizontalLayout.addWidget(self.deleteItemButton)
        self.filterData = QtWidgets.QToolButton(self.widget)
        self.filterData.setObjectName("filterData")
        self.horizontalLayout.addWidget(self.filterData)
        self.saveButton = QtWidgets.QToolButton(self.widget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.toggleEditingCheckBox = QtWidgets.QCheckBox(self.widget)
        self.toggleEditingCheckBox.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.toggleEditingCheckBox.setObjectName("toggleEditingCheckBox")
        self.horizontalLayout.addWidget(self.toggleEditingCheckBox)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(AttributesTable)
        self.editFieldButton.clicked.connect(AttributesTable.edit_field)
        self.addItemButton.clicked.connect(AttributesTable.add_item)
        self.deleteItemButton.clicked.connect(AttributesTable.delete_item)
        self.toggleEditingCheckBox.stateChanged['int'].connect(AttributesTable.toggle_editing_changed)
        self.filterData.clicked.connect(AttributesTable.filter_data)
        self.saveButton.clicked.connect(AttributesTable.save)
        QtCore.QMetaObject.connectSlotsByName(AttributesTable)

    def retranslateUi(self, AttributesTable):
        _translate = QtCore.QCoreApplication.translate
        AttributesTable.setWindowTitle(_translate("AttributesTable", "Attributes Table"))
        item = self.dataTable.verticalHeaderItem(0)
        item.setText(_translate("AttributesTable", "1"))
        item = self.dataTable.verticalHeaderItem(1)
        item.setText(_translate("AttributesTable", "2"))
        item = self.dataTable.verticalHeaderItem(2)
        item.setText(_translate("AttributesTable", "3"))
        item = self.dataTable.verticalHeaderItem(3)
        item.setText(_translate("AttributesTable", "4"))
        item = self.dataTable.verticalHeaderItem(4)
        item.setText(_translate("AttributesTable", "5"))
        item = self.dataTable.horizontalHeaderItem(0)
        item.setText(_translate("AttributesTable", "列1"))
        item = self.dataTable.horizontalHeaderItem(1)
        item.setText(_translate("AttributesTable", "新建列"))
        item = self.dataTable.horizontalHeaderItem(2)
        item.setText(_translate("AttributesTable", "列2"))
        item = self.dataTable.horizontalHeaderItem(3)
        item.setText(_translate("AttributesTable", "3"))
        item = self.dataTable.horizontalHeaderItem(4)
        item.setText(_translate("AttributesTable", "test5"))
        __sortingEnabled = self.dataTable.isSortingEnabled()
        self.dataTable.setSortingEnabled(False)
        item = self.dataTable.item(1, 1)
        item.setText(_translate("AttributesTable", "test1"))
        item = self.dataTable.item(2, 2)
        item.setText(_translate("AttributesTable", "test2"))
        self.dataTable.setSortingEnabled(__sortingEnabled)
        self.editFieldButton.setText(_translate("AttributesTable", "Edit Field"))
        self.addItemButton.setText(_translate("AttributesTable", "Add Item"))
        self.deleteItemButton.setText(_translate("AttributesTable", "Delete Item"))
        self.filterData.setText(_translate("AttributesTable", "Filter"))
        self.saveButton.setText(_translate("AttributesTable", "Save"))
        self.toggleEditingCheckBox.setText(_translate("AttributesTable", "Togle Editing"))
