# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file '_mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.3.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QHBoxLayout, QMainWindow, QMenu,
    QMenuBar, QSizePolicy, QStatusBar, QToolBar,
    QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(820, 597)
        MainWindow.setMinimumSize(QSize(600, 400))
        MainWindow.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        MainWindow.setAnimated(True)
        self.actionProjectNew = QAction(MainWindow)
        self.actionProjectNew.setObjectName(u"actionProjectNew")
        self.actionProjectOpen = QAction(MainWindow)
        self.actionProjectOpen.setObjectName(u"actionProjectOpen")
        self.actionProjectSave = QAction(MainWindow)
        self.actionProjectSave.setObjectName(u"actionProjectSave")
        self.actionExit = QAction(MainWindow)
        self.actionExit.setObjectName(u"actionExit")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        self.actionPasteAs = QAction(MainWindow)
        self.actionPasteAs.setObjectName(u"actionPasteAs")
        self.actionCopyLayer = QAction(MainWindow)
        self.actionCopyLayer.setObjectName(u"actionCopyLayer")
        self.actionEnableEditing = QAction(MainWindow)
        self.actionEnableEditing.setObjectName(u"actionEnableEditing")
        self.actionEnableEditing.setCheckable(True)
        self.actionShowToolBar = QAction(MainWindow)
        self.actionShowToolBar.setObjectName(u"actionShowToolBar")
        self.actionShowToolBar.setCheckable(True)
        self.actionShowToolBar.setChecked(True)
        self.actionSaveImage = QAction(MainWindow)
        self.actionSaveImage.setObjectName(u"actionSaveImage")
        self.actionProjectSaveAs = QAction(MainWindow)
        self.actionProjectSaveAs.setObjectName(u"actionProjectSaveAs")
        self.actionNewShapefileLayer = QAction(MainWindow)
        self.actionNewShapefileLayer.setObjectName(u"actionNewShapefileLayer")
        self.actionOptions = QAction(MainWindow)
        self.actionOptions.setObjectName(u"actionOptions")
        self.actionAddLayer = QAction(MainWindow)
        self.actionAddLayer.setObjectName(u"actionAddLayer")
        self.actionNew_MultiPoint_Layer = QAction(MainWindow)
        self.actionNew_MultiPoint_Layer.setObjectName(u"actionNew_MultiPoint_Layer")
        self.actionNew_Polyline_Layer = QAction(MainWindow)
        self.actionNew_Polyline_Layer.setObjectName(u"actionNew_Polyline_Layer")
        self.actionNew_MultiPolyline_Layer = QAction(MainWindow)
        self.actionNew_MultiPolyline_Layer.setObjectName(u"actionNew_MultiPolyline_Layer")
        self.actionNew_Polygon_Layer = QAction(MainWindow)
        self.actionNew_Polygon_Layer.setObjectName(u"actionNew_Polygon_Layer")
        self.actionNew_MultiPolygon_Layer = QAction(MainWindow)
        self.actionNew_MultiPolygon_Layer.setObjectName(u"actionNew_MultiPolygon_Layer")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.horizontalLayout_2 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.mainLayout = QHBoxLayout()
        self.mainLayout.setObjectName(u"mainLayout")

        self.horizontalLayout_2.addLayout(self.mainLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 820, 22))
        self.menuLayer = QMenu(self.menuBar)
        self.menuLayer.setObjectName(u"menuLayer")
        self.menuCreateLayer = QMenu(self.menuLayer)
        self.menuCreateLayer.setObjectName(u"menuCreateLayer")
        self.menuSettings = QMenu(self.menuBar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuVector = QMenu(self.menuBar)
        self.menuVector.setObjectName(u"menuVector")
        self.menuRaster = QMenu(self.menuBar)
        self.menuRaster.setObjectName(u"menuRaster")
        self.menuHelp = QMenu(self.menuBar)
        self.menuHelp.setObjectName(u"menuHelp")
        self.menuView = QMenu(self.menuBar)
        self.menuView.setObjectName(u"menuView")
        self.menuEdit = QMenu(self.menuBar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuProject = QMenu(self.menuBar)
        self.menuProject.setObjectName(u"menuProject")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QStatusBar(MainWindow)
        self.statusBar.setObjectName(u"statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QToolBar(MainWindow)
        self.toolBar.setObjectName(u"toolBar")
        self.toolBar.setAllowedAreas(Qt.BottomToolBarArea|Qt.TopToolBarArea)
        MainWindow.addToolBar(Qt.TopToolBarArea, self.toolBar)

        self.menuBar.addAction(self.menuProject.menuAction())
        self.menuBar.addAction(self.menuEdit.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuLayer.menuAction())
        self.menuBar.addAction(self.menuVector.menuAction())
        self.menuBar.addAction(self.menuRaster.menuAction())
        self.menuBar.addAction(self.menuSettings.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.menuLayer.addAction(self.menuCreateLayer.menuAction())
        self.menuLayer.addAction(self.actionAddLayer)
        self.menuLayer.addAction(self.actionCopyLayer)
        self.menuLayer.addSeparator()
        self.menuLayer.addAction(self.actionEnableEditing)
        self.menuCreateLayer.addAction(self.actionNewShapefileLayer)
        self.menuCreateLayer.addAction(self.actionNew_MultiPoint_Layer)
        self.menuCreateLayer.addAction(self.actionNew_Polyline_Layer)
        self.menuCreateLayer.addAction(self.actionNew_MultiPolyline_Layer)
        self.menuCreateLayer.addAction(self.actionNew_Polygon_Layer)
        self.menuCreateLayer.addAction(self.actionNew_MultiPolygon_Layer)
        self.menuSettings.addAction(self.actionOptions)
        self.menuHelp.addAction(self.actionAbout)
        self.menuView.addAction(self.actionShowToolBar)
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addAction(self.actionPasteAs)
        self.menuEdit.addSeparator()
        self.menuProject.addAction(self.actionProjectNew)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionProjectOpen)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionProjectSave)
        self.menuProject.addAction(self.actionProjectSaveAs)
        self.menuProject.addAction(self.actionSaveImage)
        self.menuProject.addSeparator()
        self.menuProject.addAction(self.actionExit)
        self.toolBar.addAction(self.actionAddLayer)

        self.retranslateUi(MainWindow)
        self.actionProjectNew.triggered.connect(MainWindow.new_project)
        self.actionProjectOpen.triggered.connect(MainWindow.open_project)
        self.actionProjectSave.triggered.connect(MainWindow.save_project)
        self.actionProjectSaveAs.triggered.connect(MainWindow.save_project_as)
        self.actionExit.triggered.connect(MainWindow.exit_app)
        self.actionAbout.triggered.connect(MainWindow.show_about_page)
        self.actionAddLayer.triggered.connect(MainWindow.add_layer)
        self.actionOptions.triggered.connect(MainWindow.show_options_page)
        self.actionShowToolBar.toggled.connect(self.toolBar.setVisible)
        self.actionEnableEditing.toggled.connect(MainWindow.switch_editing)
        self.actionCopyLayer.triggered.connect(MainWindow.copy_layer)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u03c0GIS", None))
        self.actionProjectNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionProjectOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(shortcut)
        self.actionProjectOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionProjectSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionProjectSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionExit.setText(QCoreApplication.translate("MainWindow", u"Exit \u03c0GIS", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut Features", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy Features", None))
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste Features", None))
        self.actionPasteAs.setText(QCoreApplication.translate("MainWindow", u"Paste As", None))
        self.actionCopyLayer.setText(QCoreApplication.translate("MainWindow", u"Copy Layer", None))
        self.actionEnableEditing.setText(QCoreApplication.translate("MainWindow", u"Enable Editing", None))
        self.actionShowToolBar.setText(QCoreApplication.translate("MainWindow", u"Show Tool Bar", None))
        self.actionSaveImage.setText(QCoreApplication.translate("MainWindow", u"Save Map As Image", None))
        self.actionProjectSaveAs.setText(QCoreApplication.translate("MainWindow", u"Save As", None))
#if QT_CONFIG(shortcut)
        self.actionProjectSaveAs.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionNewShapefileLayer.setText(QCoreApplication.translate("MainWindow", u"New Point Layer", None))
        self.actionOptions.setText(QCoreApplication.translate("MainWindow", u"Options", None))
        self.actionAddLayer.setText(QCoreApplication.translate("MainWindow", u"Add Layer", None))
        self.actionNew_MultiPoint_Layer.setText(QCoreApplication.translate("MainWindow", u"New MultiPoint Layer", None))
        self.actionNew_Polyline_Layer.setText(QCoreApplication.translate("MainWindow", u"New Polyline Layer", None))
        self.actionNew_MultiPolyline_Layer.setText(QCoreApplication.translate("MainWindow", u"New MultiPolyline Layer", None))
        self.actionNew_Polygon_Layer.setText(QCoreApplication.translate("MainWindow", u"New Polygon Layer", None))
        self.actionNew_MultiPolygon_Layer.setText(QCoreApplication.translate("MainWindow", u"New MultiPolygon Layer", None))
        self.menuLayer.setTitle(QCoreApplication.translate("MainWindow", u"Layer", None))
        self.menuCreateLayer.setTitle(QCoreApplication.translate("MainWindow", u"Create Layer", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.menuVector.setTitle(QCoreApplication.translate("MainWindow", u"Vector", None))
        self.menuRaster.setTitle(QCoreApplication.translate("MainWindow", u"Raster", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuProject.setTitle(QCoreApplication.translate("MainWindow", u"Project", None))
        self.toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"toolBar", None))
    # retranslateUi

